# Generated by Django 2.2.7 on 2019-11-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Título')),
                ('date', models.DateTimeField(verbose_name='Data de publicação')),
                ('arq', models.FileField(upload_to='')),
            ],
        ),
    ]
