# Generated by Django 2.2.7 on 2019-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='date',
            field=models.DateField(verbose_name='Data de publicação'),
        ),
    ]
