# Generated by Django 2.2.7 on 2019-11-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191115_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='arq',
            field=models.FileField(upload_to='', verbose_name='Arquivo da música'),
        ),
    ]
