# Generated by Django 2.2.7 on 2019-11-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191115_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(default='teste', max_length=200, verbose_name='Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='owner',
            field=models.CharField(default='teste', max_length=200, verbose_name='Criador'),
            preserve_default=False,
        ),
    ]
