# Generated by Django 2.2.7 on 2019-11-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191115_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Música', 'verbose_name_plural': 'Músicas'},
        ),
    ]
