# Generated by Django 2.2.7 on 2019-11-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default='teste', max_length=200, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
