# Generated by Django 2.2.7 on 2019-11-19 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_playlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='blog',
        ),
        migrations.AddField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(to='core.Music'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
