# Generated by Django 2.2.7 on 2019-11-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191119_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='arq',
            field=models.FileField(null=True, upload_to='', verbose_name='Arquivo da música'),
        ),
    ]
