# Generated by Django 2.2.7 on 2019-11-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191119_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='arq',
            field=models.FileField(blank=True, upload_to='', verbose_name='Arquivo da música'),
        ),
    ]
