# Generated by Django 2.2.7 on 2019-11-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191119_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='arq',
            field=models.FileField(blank=True, upload_to='arquivos/musicas', verbose_name='Arquivo da música'),
        ),
    ]
