# Generated by Django 2.2.7 on 2019-11-26 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191126_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(to='core.Music', verbose_name='Lista de Músicas'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Criador', to=settings.AUTH_USER_MODEL, verbose_name='Criado'),
        ),
    ]
