# Generated by Django 2.2.7 on 2019-11-26 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191126_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to='core.Singer', verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Singer', verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
    ]
