# Generated by Django 2.2.7 on 2019-11-28 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_auto_20191126_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do Artista')),
                ('nationality', models.CharField(max_length=250, verbose_name='Nome do Artista')),
                ('biography', models.TextField(verbose_name='Biografia')),
                ('image', models.ImageField(upload_to='arquivos/imagens/artistas', verbose_name='Imagem do artista')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.RenameField(
            model_name='music',
            old_name='arq',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='criacao',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='modificacao',
            new_name='modification',
        ),
        migrations.RemoveField(
            model_name='album',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='music',
            name='singer',
        ),
        migrations.AddField(
            model_name='album',
            name='release',
            field=models.DateField(null=True, verbose_name='Data de publicação'),
        ),
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Duração da Música'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='contributors',
            field=models.ManyToManyField(related_name='colaboradores', to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores'),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album', to='core.Album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Atalho'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(to='core.Artist', verbose_name='Artistas'),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='core.Artist', verbose_name='Artista'),
        ),
    ]
