# Generated by Django 2.2.7 on 2019-11-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191128_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='nationality',
        ),
    ]
