# Generated by Django 2.2.7 on 2019-11-28 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191128_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='colaboradores', to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores'),
        ),
    ]
