# Generated by Django 2.2.7 on 2019-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191128_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(related_name='artist', to='core.Artist', verbose_name='Artista'),
        ),
    ]
