# Generated by Django 2.2.7 on 2019-11-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20191128_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(null=True, upload_to='arquivos/imagens/album', verbose_name='Imagem do album'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(null=True, upload_to='arquivos/imagens/playlist', verbose_name='Imagem da playlist'),
        ),
    ]
