# Generated by Django 2.2.7 on 2019-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20191128_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='teste', max_length=200, verbose_name='Atalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='teste2', max_length=200, verbose_name='Atalho'),
            preserve_default=False,
        ),
    ]
